"""Generate tleap scripts and AMBER files."""

import os
import subprocess
from pathlib import Path

# Module-level env dict that can be set by CLI
_amber_env: dict | None = None


def set_amber_env(modxna_path: Path) -> None:
    """Set up environment for AmberTools commands.

    Args:
        modxna_path: Path to modXNA installation
    """
    global _amber_env
    _amber_env = os.environ.copy()

    # modXNA is in bin/modXNA, conda_env is in bin/conda_env
    bin_dir = modxna_path.parent  # Go from bin/modXNA to bin/
    conda_bin = bin_dir / "conda_env" / "bin"
    cpptraj_bin = bin_dir / "cpptraj_install" / "bin"

    # Update PATH to include cpptraj_install/bin, conda_env/bin and modXNA
    # cpptraj_install has newer cpptraj (6.30) required by modXNA
    path_parts = [
        str(cpptraj_bin),
        str(conda_bin),
        str(modxna_path),
        _amber_env.get("PATH", ""),
    ]
    _amber_env["PATH"] = ":".join(path_parts)

    # Set AMBERHOME for AmberTools
    _amber_env["AMBERHOME"] = str(bin_dir / "conda_env")


def _get_env() -> dict | None:
    """Get the configured environment, or None to use default."""
    return _amber_env


def generate_combine_lib_script(lib_paths: dict[str, Path], output_dir: Path) -> Path:
    """Generate tleap script to combine .lib files into combined.lib.

    Args:
        lib_paths: Dictionary mapping residue names to their .lib file paths
        output_dir: Output directory for the combined library

    Returns:
        Path to the generated tleap script
    """
    script_path = output_dir / "combine_libs.leap"
    combined_lib = output_dir / "combined.lib"

    lines = [
        "# Combine individual residue libraries into a single library",
        "# Generated by modXNA pipeline",
        "",
    ]

    # Load each library
    for resname, lib_path in lib_paths.items():
        lines.append(f"loadoff {lib_path}")

    # Save each residue to combined library
    # tleap doesn't support wildcard *, so save each unit individually
    lines.append("")
    resnames = list(lib_paths.keys())
    # Create a list to save all residues
    lines.append(f"saveoff {{ {' '.join(resnames)} }} {combined_lib}")
    lines.append("quit")
    lines.append("")

    with open(script_path, "w") as f:
        f.write("\n".join(lines))

    return script_path


def generate_build_script(
    sequence: list[str],
    output_dir: Path,
    frcmod_path: Path,
    solvate: bool = True,
    salt_conc: float = 0.15
) -> Path:
    """Generate tleap script to build the oligonucleotide.

    Args:
        sequence: List of residue names in order
        output_dir: Output directory
        frcmod_path: Path to frcmod.modxna parameter file
        solvate: Whether to solvate the system
        salt_conc: Salt concentration in M (default 0.15 for 150mM)

    Returns:
        Path to the generated tleap script
    """
    script_path = output_dir / "build_aso.leap"
    combined_lib = output_dir / "combined.lib"

    lines = [
        "# Build oligonucleotide from modXNA residues",
        "# Generated by modXNA pipeline",
        "",
        "# Load force fields",
        "source leaprc.DNA.OL15",
        "source leaprc.RNA.OL3",
        "source leaprc.water.opc",
        "",
        "# Load modXNA residue library and parameters",
        f"loadoff {combined_lib}",
        f"loadamberparams {frcmod_path}",
        "",
        "# Build the oligonucleotide sequence",
    ]

    # Build sequence command: ASO = sequence{RES1 RES2 ...}
    seq_str = " ".join(sequence)
    lines.append(f"ASO = sequence{{ {seq_str} }}")
    lines.append("")

    if solvate:
        lines.extend([
            "# Solvate in truncated octahedral OPC water box",
            "solvateoct ASO OPCBOX 9.0",
            "",
            "# Neutralize the system",
            "addionsrand ASO Na+ 0",
            "",
        ])

        # Add salt ions for desired concentration
        # For 150mM NaCl in typical system, need to calculate based on box volume
        # Using approximate ion counts - tleap will handle the actual placement
        if salt_conc > 0:
            lines.extend([
                f"# Add {salt_conc*1000:.0f}mM NaCl",
                "# Note: Ion counts are approximate; actual concentration depends on box size",
                "# For ~9A buffer, typically need ~40-60 ion pairs for 150mM",
                "addionsrand ASO Na+ 50",
                "addionsrand ASO Cl- 50",
                "",
            ])

    lines.extend([
        "# Save topology and coordinates",
        f"saveamberparm ASO {output_dir}/aso.parm7 {output_dir}/aso.crd",
        f"savepdb ASO {output_dir}/aso.pdb",
        "",
        "quit",
        "",
    ])

    with open(script_path, "w") as f:
        f.write("\n".join(lines))

    return script_path


def generate_hmr_script(output_dir: Path) -> Path:
    """Generate parmed script to apply hydrogen mass repartitioning.

    Args:
        output_dir: Output directory containing aso.parm7

    Returns:
        Path to the generated parmed script
    """
    script_path = output_dir / "hmr.parmed"

    lines = [
        "# Apply hydrogen mass repartitioning for 4fs timestep",
        "# Generated by modXNA pipeline",
        "",
        f"parm {output_dir}/aso.parm7",
        "HMassRepartition",
        f"outparm {output_dir}/aso.hmr.parm7",
        "quit",
        "",
    ]

    with open(script_path, "w") as f:
        f.write("\n".join(lines))

    return script_path


def run_tleap(script_path: Path) -> bool:
    """Run tleap script, return success status.

    Args:
        script_path: Path to the tleap script to run

    Returns:
        True if tleap ran successfully, False otherwise
    """
    try:
        result = subprocess.run(
            ["tleap", "-f", str(script_path)],
            capture_output=True,
            text=True,
            check=False,  # Don't raise on non-zero exit
            env=_get_env()
        )

        # Check for errors in output - look for tleap's error summary
        # tleap prints "Exiting LEaP: Errors = N" at the end
        if "FATAL" in result.stdout:
            print(f"tleap errors:\n{result.stdout}")
            return False

        # Check the exit summary line for actual errors
        if "Errors = " in result.stdout:
            import re
            error_match = re.search(r"Errors = (\d+)", result.stdout)
            if error_match and int(error_match.group(1)) > 0:
                print(f"tleap errors:\n{result.stdout}")
                return False

        if result.returncode != 0:
            print(f"tleap failed with return code {result.returncode}")
            print(f"stdout: {result.stdout}")
            print(f"stderr: {result.stderr}")
            return False

        return True

    except FileNotFoundError:
        print("Error: tleap not found. Make sure AmberTools is installed and in PATH.")
        return False
    except Exception as e:
        print(f"Error running tleap: {e}")
        return False


def run_parmed(script_path: Path) -> bool:
    """Run parmed script, return success status.

    Args:
        script_path: Path to the parmed script to run

    Returns:
        True if parmed ran successfully, False otherwise
    """
    try:
        result = subprocess.run(
            ["parmed", "-i", str(script_path)],
            capture_output=True,
            text=True,
            check=False,
            env=_get_env()
        )

        if result.returncode != 0:
            print(f"parmed failed with return code {result.returncode}")
            print(f"stdout: {result.stdout}")
            print(f"stderr: {result.stderr}")
            return False

        return True

    except FileNotFoundError:
        print("Error: parmed not found. Make sure AmberTools is installed and in PATH.")
        return False
    except Exception as e:
        print(f"Error running parmed: {e}")
        return False


def run_minimization(output_dir: Path) -> bool:
    """Run 2-stage minimization using sander to fix structural clashes.

    As noted in the LiveCoMS tutorial: LEaP creates a linearized structure
    with overlaps. Running minimization produces a clash-free structure.

    Stages:
        1. min1: Restrained minimization (solvent only, solute fixed)
        2. min2: Full system minimization

    Args:
        output_dir: Output directory containing aso.parm7, aso.crd, md_inputs/

    Returns:
        True if successful, outputs aso.min.rst7 and aso.min.pdb
    """
    md_inputs = output_dir / "md_inputs"
    prmtop = output_dir / "aso.parm7"
    inpcrd = output_dir / "aso.crd"

    # Check required files exist
    if not prmtop.exists():
        print(f"Error: topology not found: {prmtop}")
        return False
    if not inpcrd.exists():
        print(f"Error: coordinates not found: {inpcrd}")
        return False
    if not (md_inputs / "min1.in").exists():
        print(f"Error: min1.in not found in {md_inputs}")
        return False

    try:
        # Stage 1: Restrained minimization (solvent only)
        print("  Running min1 (restrained)...")
        result = subprocess.run(
            [
                "sander", "-O",
                "-i", str(md_inputs / "min1.in"),
                "-o", str(output_dir / "min1.out"),
                "-p", str(prmtop),
                "-c", str(inpcrd),
                "-r", str(output_dir / "min1.rst7"),
                "-ref", str(inpcrd),
            ],
            capture_output=True,
            text=True,
            check=False,
            env=_get_env(),
        )

        if result.returncode != 0:
            print(f"min1 failed with return code {result.returncode}")
            print(f"stderr: {result.stderr}")
            return False

        # Stage 2: Full system minimization
        print("  Running min2 (full system)...")
        result = subprocess.run(
            [
                "sander", "-O",
                "-i", str(md_inputs / "min2.in"),
                "-o", str(output_dir / "min2.out"),
                "-p", str(prmtop),
                "-c", str(output_dir / "min1.rst7"),
                "-r", str(output_dir / "aso.min.rst7"),
            ],
            capture_output=True,
            text=True,
            check=False,
            env=_get_env(),
        )

        if result.returncode != 0:
            print(f"min2 failed with return code {result.returncode}")
            print(f"stderr: {result.stderr}")
            return False

        # Convert minimized structure to PDB using cpptraj
        print("  Converting to PDB...")
        cpptraj_script = f"""\
parm {prmtop}
trajin {output_dir}/aso.min.rst7
trajout {output_dir}/aso.min.pdb pdb
run
quit
"""
        result = subprocess.run(
            ["cpptraj"],
            input=cpptraj_script,
            capture_output=True,
            text=True,
            check=False,
            env=_get_env(),
        )

        if result.returncode != 0:
            print(f"cpptraj failed with return code {result.returncode}")
            print(f"stderr: {result.stderr}")
            return False

        # Verify output
        min_pdb = output_dir / "aso.min.pdb"
        if not min_pdb.exists():
            print("Error: aso.min.pdb was not created")
            return False

        print(f"  Minimized structure: {min_pdb}")
        return True

    except FileNotFoundError as e:
        print(f"Error: required program not found: {e}")
        print("Make sure AmberTools (sander, cpptraj) is installed and in PATH.")
        return False
    except Exception as e:
        print(f"Error during minimization: {e}")
        return False
