#!/usr/bin/env python3
"""CLI entrypoint for the patent-collate pipeline.

Three-stage LLM-powered extraction of structured data from USPTO patent XML tables:
  1. XML → JSON conversion (per-table extraction scripts generated by LLM)
  2. HELM chemistry annotation (nucleotide-level structure strings)
  3. Schema collation (mapping extracted data to user-defined schemas)
"""

import argparse
import json
import re
import sys


def build_table_data(successful_responses, file_to_canonical):
    """Post-process step 1 output into the table_data dict used by later stages."""
    table_data = {}

    for response in successful_responses:
        custom_id = response['custom_id']
        data = json.loads(response['json_output'])

        if custom_id not in table_data:
            table_data[custom_id] = {
                'canonical_link': False,
                'compound_data': {}
            }

        for entry in data.get('entries', []):
            compound_id = entry.get('compound_id')
            if compound_id is None:
                continue

            match = re.search(r'\d+', str(compound_id))
            if match is None:
                continue
            clean_id = match.group()

            if len(clean_id) <= 3:
                continue

            compound_data = entry.get('data')
            if clean_id not in table_data[custom_id]['compound_data']:
                table_data[custom_id]['compound_data'][clean_id] = []
            table_data[custom_id]['compound_data'][clean_id].append(compound_data)

    for duplicate_path, canonical_path in file_to_canonical.items():
        if duplicate_path != canonical_path and canonical_path in table_data:
            table_data[duplicate_path] = {
                'canonical_link': canonical_path,
                'compound_data': {}
            }

    canonical_count = sum(1 for v in table_data.values() if v['canonical_link'] is False)
    duplicate_count = sum(1 for v in table_data.values() if v['canonical_link'] is not False)
    print(f"Table data: {len(table_data)} entries ({canonical_count} canonical, {duplicate_count} duplicates)")
    return table_data


def build_custom_ids_to_annotate(table_data):
    """Determine which compounds in which tables need HELM annotation.

    Groups tables by USPTO patent ID and tracks seen compound IDs per patent
    to avoid re-annotating compounds already present in earlier tables.
    """
    custom_ids = table_data.keys()
    uspto_ids = list(set(re.search(r'(US\w+?)_', cid).group(1) for cid in custom_ids))

    custom_ids_to_annotate = {}
    for uspto_id in uspto_ids:
        seen_mol_ids = set()
        for custom_id in sorted(cid for cid in custom_ids if uspto_id in cid):
            if table_data[custom_id]['canonical_link'] is False:
                new_mol_ids = set()
                for mol_id in table_data[custom_id]['compound_data'].keys():
                    if mol_id not in seen_mol_ids:
                        new_mol_ids.add(mol_id)
                seen_mol_ids.update(new_mol_ids)
                if new_mol_ids:
                    custom_ids_to_annotate[custom_id] = list(new_mol_ids)
            else:
                canonical = table_data[custom_id]['canonical_link']
                seen_mol_ids.update(set(table_data[canonical]['compound_data'].keys()))

    print(f"Will annotate {len(custom_ids_to_annotate)} tables for HELM")
    return custom_ids_to_annotate


def make_client(args):
    from src.client import ASOClient
    return ASOClient(
        model=args.model,
        verbosity="low",
        reasoning_effort=args.reasoning_effort,
        service_tier=args.service_tier if args.service_tier != "none" else None,
        max_workers=args.max_workers,
        debug=args.debug,
        api_key=args.api_key,
        cache_dir=args.cache_dir,
    )


def run_step1(args):
    client = make_client(args)
    successful, failed, file_to_canonical = client.agentic_json_conversion(
        input_directory=args.input_dir,
        n_files=args.n_files,
        max_attempts=args.max_attempts,
    )
    print(f"Step 1 complete: {len(successful)} succeeded, {len(failed)} failed")

    table_data = build_table_data(successful, file_to_canonical)

    with open(args.output, 'w') as f:
        json.dump(table_data, f, indent=2)
    print(f"Saved to {args.output}")
    print(f"Cost: {client.calculate_cost()}")
    return table_data


def run_step2(args, table_data=None):
    if table_data is None:
        with open(args.table_data, 'r') as f:
            table_data = json.load(f)

    custom_ids_to_annotate = build_custom_ids_to_annotate(table_data)
    client = make_client(args)
    helm_annotations = client.agentic_helm_conversion(
        table_data,
        custom_ids_to_annotate,
        max_attempts=args.max_attempts,
    )

    total_compounds = sum(len(v) for v in helm_annotations.values())
    print(f"Step 2 complete: {total_compounds} compounds annotated across {len(helm_annotations)} tables")

    with open(args.output, 'w') as f:
        json.dump(helm_annotations, f, indent=2)
    print(f"Saved to {args.output}")
    print(f"Cost: {client.calculate_cost()}")
    return helm_annotations


def run_step3(args, table_data=None):
    if table_data is None:
        with open(args.table_data, 'r') as f:
            table_data = json.load(f)

    table_data = {k: v for k, v in table_data.items() if v['canonical_link'] is False}

    with open(args.schema, 'r') as f:
        schema_data = json.load(f)

    client = make_client(args)
    collated_data = client.test_and_retry_collate_script(
        table_data,
        schema_data,
        max_attempts=args.max_attempts,
    )

    with open(args.output, 'w') as f:
        json.dump(collated_data, f, indent=2)
    print(f"Step 3 complete. Saved to {args.output}")
    print(f"Cost: {client.calculate_cost()}")
    return collated_data


def run_all(args):
    import os
    os.makedirs(args.output_dir, exist_ok=True)

    args.output = os.path.join(args.output_dir, "step1_table_data.json")
    table_data = run_step1(args)

    args.output = os.path.join(args.output_dir, "step2_helm_annotations.json")
    run_step2(args, table_data=table_data)

    args.output = os.path.join(args.output_dir, "step3_collation_results.json")
    run_step3(args, table_data=table_data)

    print(f"\nPipeline complete. Results in {args.output_dir}/")


def main():
    parser = argparse.ArgumentParser(
        description="Patent table extraction pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # Global arguments
    parser.add_argument("--model", default="gpt-5-mini")
    parser.add_argument("--api-key", default=None, help="OpenAI API key (or set OPENAI_API_KEY)")
    parser.add_argument("--reasoning-effort", default="medium", choices=["low", "medium", "high"])
    parser.add_argument("--service-tier", default="flex", choices=["flex", "default", "none"])
    parser.add_argument("--max-workers", type=int, default=50)
    parser.add_argument("--max-attempts", type=int, default=5)
    parser.add_argument("--debug", action="store_true")
    parser.add_argument("--cache-dir", default=None, help="Override cache directory")

    subparsers = parser.add_subparsers(dest="command", required=True)

    # Step 1
    p1 = subparsers.add_parser("step1", help="XML → JSON table extraction")
    p1.add_argument("--input-dir", required=True, help="Directory containing patent XML files")
    p1.add_argument("--output", default="step1_table_data.json")
    p1.add_argument("--n-files", type=int, default=None, help="Limit number of files to process")

    # Step 2
    p2 = subparsers.add_parser("step2", help="HELM chemistry annotation")
    p2.add_argument("--table-data", required=True, help="Path to step 1 output JSON")
    p2.add_argument("--output", default="step2_helm_annotations.json")

    # Step 3
    p3 = subparsers.add_parser("step3", help="Schema collation")
    p3.add_argument("--table-data", required=True, help="Path to step 1 output JSON")
    p3.add_argument("--schema", required=True, help="Path to schema JSON file")
    p3.add_argument("--output", default="step3_collation_results.json")

    # Run all
    pa = subparsers.add_parser("run-all", help="Run full pipeline (steps 1-3)")
    pa.add_argument("--input-dir", required=True, help="Directory containing patent XML files")
    pa.add_argument("--schema", required=True, help="Path to schema JSON file")
    pa.add_argument("--output-dir", default=".", help="Output directory for results")
    pa.add_argument("--n-files", type=int, default=None, help="Limit number of files to process")

    args = parser.parse_args()

    dispatch = {
        "step1": run_step1,
        "step2": run_step2,
        "step3": run_step3,
        "run-all": run_all,
    }
    dispatch[args.command](args)


if __name__ == "__main__":
    main()
